version: '3.8'
services:

  #App Boilerplate 
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-app
    restart: always
    tty: true
    working_dir: /var/www/
    ports:
      - 3001:3000 #Production port
      - 5000:5000 #Development port
      - 9027:9026 #Hmr development port
    volumes:
      - ./:/var/www/
    networks:
      - proxy
      - app-network
      


#Docker Networks
networks:
  app-network:
    name: ${APP_NAME}-network
    driver: bridge
  proxy:
    name: nginx-proxy
    external: true
