services:
  frontend:
    build:
      context: ./frontend
    restart: on-failure
    tty: true
    command: yarn preview --host 0.0.0.0 --port 5000
    ports: [5000]
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
    command: dotnet backend.dll
    restart: always
    ports: [8081]
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8081
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - dbdata6:/data/db

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend

        # certbot:
        #   image: certbot/certbot
        #   container_name: certbot
        #   volumes:
        #     - ./certbot/conf:/etc/letsencrypt
        #     - ./certbot/www:/var/www/certbot
        #   command: certonly --webroot -w /var/www/certbot --force-renewal --email poseaydone@ya.ru -d ultratype.ru --agree-tos
        #   depends_on:
        #     - nginx

volumes:
  dbdata6:
