services:
  frontend:
    build:
      context: ./frontend
    restart: on-failure
    ports:
      - 5000:5000
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - BODY_SIZE_LIMIT=Infinity

  backend:
    build:
      context: ./backend
    command: dotnet backend.dll
    ports:
      - 9000:9000
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:9000
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - dbdata6:/data/db


volumes:
  dbdata6:
