import { ILetters } from "../models/ILetters";

export const lettersConst : ILetters  = {
    en: {
        e: {
            wpm: 0,
            errorRate: 0,
            confidence: 0,
            typedCounter: 0,
            errorCounter: 0,
            timeElapsed: 0,
        },
        n: {
            wpm: 0,
            errorRate: 0,
            confidence: 0,
            typedCounter: 0,
            errorCounter: 0,
            timeElapsed: 0,
        },
        i: {
            wpm: 0,
            errorRate: 0,
            confidence: 0,
            typedCounter: 0,
            errorCounter: 0,
            timeElapsed: 0,
        },
        t: {
            wpm: 0,
            errorRate: 0,
            confidence: 0,
            typedCounter: 0,
            errorCounter: 0,
            timeElapsed: 0,
        },
        r: {
            wpm: 0,
            errorRate: 0,
            confidence: 0,
            typedCounter: 0,
            errorCounter: 0,
            timeElapsed: 0,
        },
        l: {
            wpm: 0,
            errorRate: 0,
            confidence: 0,
            typedCounter: 0,
            errorCounter: 0,
            timeElapsed: 0,
        },
    },
    ru: {
        е: {
            wpm: 0,
            errorRate: 0,
            confidence: 0,
            typedCounter: 0,
            errorCounter: 0,
            timeElapsed: 0,
        },
        и: {
            wpm: 0,
            errorRate: 0,
            confidence: 0,
            typedCounter: 0,
            errorCounter: 0,
            timeElapsed: 0,
        },
        а: {
            wpm: 0,
            errorRate: 0,
            confidence: 0,
            typedCounter: 0,
            errorCounter: 0,
            timeElapsed: 0,
        },
        о: {
            wpm: 0,
            errorRate: 0,
            confidence: 0,
            typedCounter: 0,
            errorCounter: 0,
            timeElapsed: 0,
        },
        т: {
            wpm: 0,
            errorRate: 0,
            confidence: 0,
            typedCounter: 0,
            errorCounter: 0,
            timeElapsed: 0,
        },
        н: {
            wpm: 0,
            errorRate: 0,
            confidence: 0,
            typedCounter: 0,
            errorCounter: 0,
            timeElapsed: 0,
        },
    }
}